# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Retag Docker image in AWS ECR without pulling
description: Retag existing Docker image in AWS ECR without pulling
author: 'Andrey Bronin <abronin@gmail.com>'
branding:
  icon: 'tag'
  color: 'blue'

inputs:
  aws-account-id:
    description: 'The AWS account ID associated with the registry that contains the image to retag (the default registry of user is assumed)'
    required: false
  aws-region:
    description: 'AWS Region (e.g. us-east-2; not required if you provide AWS_REGION env variable)'
    required: false
  repository:
    description: 'ECR repository name (e.g. namespace/image)'
    required: true
  tag:
    description: 'Image tag you want to add new tags to (e.g. latest)'
    required: true
  new-tags:
    description: 'List of tags you want to add (e.g. v1.2.3, production, sha-1234asdf)'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
